version: '3.9'

services:
  mongo:
    image: mongo:5.0.16
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sharecode
    volumes:
      - ./db_init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro