GET http://localhost:8081/format/all

###
POST http://localhost:8081/paste/new
Content-Type: application/json

{
  "data": "@Repository\npublic interface FormatRepository extends JpaRepository<FormatEntity, Integer> {\n\t\t}",
  "formatTypeId": "644ab384b10efa2ebd8b7b7f",
  "expireDate": "2023-04-27T20:42:43.143558"
}
